name: Publish Package to Nexus

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to Nexus
        run: |
          echo "//localhost:8081/repository/npm-local/:_auth=$(echo -n ${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }} | base64)" > .npmrc
          echo "registry=http://localhost:8081/repository/npm-local/" >> .npmrc
          echo "always-auth=true" >> .npmrc
          npm publish
